version: '3.9'

x-healthcheck: &healthcheck
  healthcheck:
    test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 10s

services:
  catalog-api:
    build:
      context: ./catalog
      dockerfile: Dockerfile
    container_name: catalog-api
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      MYSQL_DATABASE: catalog
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: catalog-db
    depends_on:
      catalog-db:
        condition: service_healthy
    networks:
      - catalog

  catalog-db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog
    networks:
          - catalog
    volumes:
      - catalog:/var/lib/mysql
    <<: *healthcheck

networks:
  catalog:

volumes:
  catalog:
