version: '3.9'

x-healthcheck: &healthcheck
  healthcheck:
    test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 10s

services:
  products-api:
    build:
      context: ./products
      dockerfile: Dockerfile
    container_name: products-api
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      MYSQL_DATABASE: product
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: products-db
    depends_on:
      products-db:
        condition: service_healthy
    networks:
      - products

  products-db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product
    networks:
          - products
    volumes:
      - products:/var/lib/mysql
    <<: *healthcheck

networks:
  products:

volumes:
  products:
